AWS Request verification on proxy
arempter/gargoyle-s3proxy pull request #32
Opened 2018-10-09 08:15 UTC by arempter

Verifies AWS signature V2 and V4 on proxy upon request arrival, before request is checked in Ranger policies and sent to Ceph

2018-10-09 12:24 UTC, kr7ysztof requested changes
structure of a long class

2018-10-09 12:24 UTC, kr7ysztof commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/api/ProxyService.scala
>    // TODO: Implement request authentication using aws signing
TODO  is done so can be removed

2018-10-09 12:24 UTC, kr7ysztof commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/provider/SignatureProviderAws.scala
> +  def isUserAuthenticated(httpRequest: HttpRequest, awsSecretKey: AwsSecretKey): Boolean = {
Too long class
can we split it? e.g. 
in the class we will have only the implementation of  `def isUserAuthenticated` and the amazonwas things which uses:
```
import com.amazonaws.http.HttpMethodName
import com.amazonaws.services.s3.Headers
import com.amazonaws.services.s3.internal.RestUtils
import com.amazonaws.util.DateUtils
import com.amazonaws.{ DefaultRequest, SignableRequest }
```

have in a seperate class.

2018-10-09 12:24 UTC, kr7ysztof commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/provider/SignatureProviderAws.scala
> +    val newSignature: Option[String] =
maybe just skip the newSignature val and:
```scala
      if (incomingRequest.getHeaders.containsKey("Authorization")) {
        val proxySignature = getSignatureFromAuthorization(incomingRequest.getHeaders.get("Authorization"))
        logger.debug(s"New Signature $proxySignature Original Signature: ${awsHeaders.signature.getOrElse("")}")
        awsHeaders.signature.getOrElse("") == proxySignature
      } else false
```

2018-10-09 12:24 UTC, kr7ysztof commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/provider/SignatureProviderAws.scala
> +    // add headers from original request before sign
instead of comment it is better to create a private method with a good name:
```scala
def addHeaderToRequest(awsHeaders: ....): incomingRequest 
```

2018-10-10 07:25 UTC, kr7ysztof reviewed
Do we have time to split the two implementations (V2, V4)? If not we will do it next time.

2018-10-10 07:25 UTC, kr7ysztof commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/provider/aws/SignatureHelpers.scala
> +    if (param.contains("%7E")) {
the `if/else` is not needed - just return 
```scala
param.replace("%7E", "~")
```

2018-10-10 07:25 UTC, kr7ysztof commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/provider/aws/SignatureHelpers.scala
> +  final val AWS_SIGN_V4 = "v4"
We have two implementations in the class V2 and V4 so  it is better to have separate classes.

2018-10-10 07:48 UTC, arempter commented on src/main/scala/com/ing/wbaa/gargoyle/proxy/provider/aws/SignatureHelpers.scala
> +  final val AWS_SIGN_V4 = "v4"
As discussed lets see how signature works and split it into two subclasses on next major update

2018-10-10 09:43 UTC, kr7ysztof approved these changes

2018-10-10 09:43 UTC, merged